[package]
name = "file_locksmith"
version = "0.0.0-local"
edition = "2021"
license = "MIT"
authors = ["Caelan Sayler <git@caesay.com>"]
description = "Detect what processes are locking a file or folder on Windows"
readme = "README.md"
# exclude = ["/samples"]
# homepage = "https://velopack.io"
# repository = "https://github.com/velopack/velopack.fusion"
# keywords = ["update", "install", "velopack", "squirrel", "automatic-updates"]
# categories = ["development-tools"]

[lib]
name = "file_locksmith"
path = "src/lib.rs"

# [build-dependencies]
# cc = "1.0"



[build-dependencies]
cc = "1.1"