[package]
name = "filelocksmith"
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["Caelan Sayler <git@caesay.com>"]
description = "Detect what processes are locking a file or folder on Windows"
readme = "README.md"
homepage = "https://github.com/velopack/filelocksmith-rs"
repository = "https://github.com/velopack/filelocksmith-rs"
keywords = ["windows", "locksmith", "powertoys", "find", "locking"]
categories = ["development-tools"]

exclude = [
    "PowerToys/*",
    "!PowerToys/src/modules/FileLocksmith/FileLocksmithLibInterop/**/*"
]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[lib]
name = "filelocksmith"
path = "src/lib.rs"

[build-dependencies]
cc = "1.1"